### ISSUE TITLE
Can't apply custom background (sharp)

### ISSUE THREAD

**Issue by floriankapaun** [herrstucki/responsive-loader#107]
Hey.

I tried to apply a custom background color for png to jpg conversion.

Neither this:

```
options: {
    name: '[name]-[width].[ext]',
    sizes: [480, 3600],
    format: 'jpg',
    quality: 80,
    outputPath: 'images/',
    adapter: require('responsive-loader/sharp'),
    background: '#101010'
}
```

nor this:

```const x = require('image.png?background=#101010');```

is working.

The error I get from the console is:

**ERROR in image.png?background=#101010
Module build failed (from ./node_modules/responsive-loader/lib/index.js):
TypeError: resized.background is not a function**

**Comment by sgb-allen** [comment]
@floriankapaun This was removed from the sharp libray in 0.22.0. Try with sharp version 0.21.0. https://sharp.pixelplumbing.com/changelog#v0220---18supthsup-march-2019

`npm i -D sharp@0.21`

**Comment by floriankapaun** [comment]
Thanks a lot @sgb-allen. That fixed my problem!
