### ISSUE TITLE
Proposal: Change how emitted file name extensions are handled

### ISSUE THREAD

**Issue by alex-ketch** [herrstucki/responsive-loader#13]
Would you be open to a PR to change how the file extension is attached to the base file name?

I'm wary as it could potentially be breaking change, but it seems odd—and not in line with other loaders—that you need to include a trailing period when including a `name` query.

For instance with a file named `test.jpg`:
`responsive?name=[name]-[width].[ext]` outputs `test-500.jpgjpg`
`responsive?name=[name]-[width]` outputs `test-500jpg`
`responsive?name=[name]-[width].` outputs `test-500.jpg` (note the trailing period in the query)

The PR would make it so that:
- A query without a name parameter would use the default file extension
- A query with a name parameter would require a full naming structure (`[name]-[width].[ext])
- A query with an explicitly named extension would convert the file to that type and use that extension (as currently handled)

**Comment by herrstucki** [comment]
Yeah, that sounds great!

I'm not 100% sure about the last case though. What would happen when you specify `responsive?name=[name].jpg&ext=png`? I think I'm against detecting the file type from the file name, and keep using the `ext` (or maybe that should be `type`) parameter for that.
