### ISSUE TITLE
Disable emit option for server side rendering

### ISSUE THREAD

**Issue by beckend** [herrstucki/responsive-loader#25]
A simple option in plugins or the loader query perhaps?
So the loader would only return the images data and skip emit of files.

**Comment by herrstucki** [comment]
Can you elaborate on why that's needed and how it would work?

**Comment by beckend** [comment]
Stolen from [file-loader README](https://github.com/webpack/file-loader)
```js
var url = require("file-loader?emitFile=false!./file.png");
// => returns the public url but does NOT emit a file
// => returns i. e. "/public-path/0dcbbaa701328a3c262cfd45869e351f.png"
```

**Comment by beckend** [comment]
Basically server side rendering does not really need the file itself since it only serves static markup, to properly do that, it needs correct image dimensions and filenames.

**Comment by herrstucki** [comment]
Hmm, yeah, but a) why would you run webpack on a server? Isn't it better to compile the server code first and then run it? And b) why don't you need the file? 

Note: With the current implementation this would be quite slow because to get the hashed file name, the loader needs to resize the image anyway, even if the file isn't emitted.

**Comment by beckend** [comment]
It's for running in development mode.

**Comment by herrstucki** [comment]
There already _is_ an option to disable the loader (although it's not documented): add `responsiveLoader: {pass: true}` to your webpack config. But this only returns one image in the srcset (which is actually the unmodified original). It's probably also kinda broken at the moment, as in that it won't contain correct width and heights. I guess what we could do is return the same output as in the normal mode, but with unresized images for the complete srcset.

**Comment by beckend** [comment]
Alright thanks.
