### ISSUE TITLE
[Question] Webpack 2 supported?

### ISSUE THREAD

**Issue by dcworldwide** [herrstucki/responsive-loader#34]
Is this lib compatible with webpack 2? 

I've tried 

```
 @include breakpoint(mobile) {
     background-image: url('responsive?size=480!../../../../assets/hero.jpg');
  }
```

However this breaks my build. Webpack seems to no longer support the ! loader syntax?

Also would this be correct?

```
module: {
        rules: [
            {
                test: /\.(png|jpg|svg)$/,
                use: 'url-loader?limit=8192',
                include: PATHS.app,
            },
            {
                test: /\.(jpg|png|svg)$/,
                use: 'file-loader?name=[path][name].[hash].[ext]',
                include: PATHS.images,
            },
{
                test: /\.(jpg)$/,
                use: 'responsive',
                include: PATHS.images,
            }
        ]
    }
```

**Comment by herrstucki** [comment]
Hi! Webpack 2 [doesn't support the `-loader`-less syntax anymore](https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed). Writing `responsive-loader!foo.jpg` instead of `responsive!foo.jpg` should work. Please let me know if it doesn't.

**Comment by dcworldwide** [comment]
You're absolutely right...I forgot. Will re check
