### ISSUE TITLE
Options without configuring loader?

### ISSUE THREAD

**Issue by oscar-b** [herrstucki/responsive-loader#38]
In the old version, I did something like this when importing the image:

```javascript
import topImage from 'responsive-loader!./images/contact-us.jpg';
```

And then had a section with options in my webpack 2 config:

```javascript
new webpack.LoaderOptionsPlugin({
	options: {
		responsiveLoader: {
			sizes: [1000, 500, 1500],
			placeholder: true,
			placeholderSize: 20,
			quality: 75,
			name: 'images/[name]-[sha512:hash:base64:5]-[width].',
		},
	},
}),
```

But with v1.x there are only examples specifying options when responsive-loader is configured as a loader? Is there any other way to specify default settings (without LoaderOptionsPlugin since that will be deprecated eventually)?

**Comment by herrstucki** [comment]
I'm not sure that's possible. Best is to properly configure the loader.

One useful trick is to match the loader on the resourceQuery part, e.g.

```diff
module: {
  rules: [
      {
        test: /\.(png|jpg)$/,
+       resourceQuery: /responsive/,
        loader: 'responsive-loader',
        options: {
          // ...
        }
      }
  ]
}
```

Then you can import responsive images like this:

```js
import topImage from './images/contact-us.jpg?responsive';
```

**Comment by oscar-b** [comment]
That's a nice trick, thanks, will try that :)
