### ISSUE TITLE
Wrong extension

### ISSUE THREAD

**Issue by sytranlm** [herrstucki/responsive-loader#39]
```
{
    test: /\.(jpe?g|png)$/i,
    use: {
      loader: 'responsive-loader',
      options: {
        name: '[name].[hash].[ext]',
        size: 768,
        placeholder: false
      }
    }
}
```
It returns `filename.784f17d8a8c77977b1c087cc21edb553.jpgjpg` and if I remove `.[ext]` there will be no dot before `jpg`

**Comment by herrstucki** [comment]
Which version are you using? Can you create a PR with at least a failing test? Thanks.

**Comment by sytranlm** [comment]
I'm using `responsive-loader@0.7.0`. I'll try make a PR soon for this.
By the way it becomes an issue on IE only because the browser can't recognize file type.

**Comment by herrstucki** [comment]
v0.7.0 doesn't support `[ext]` as part of the `name` option. Either use `[name].[hash].` or upgrade to v1.

**Comment by herrstucki** [comment]
Please refer to the [change log](https://github.com/herrstucki/responsive-loader/blob/master/CHANGELOG.md) on how to upgrade. Cheers!

**Comment by sytranlm** [comment]
Thanks!
