### ISSUE TITLE
PHP/Blade integration

### ISSUE THREAD

**Issue by strarsis** [herrstucki/responsive-loader#43]
Can I also use this loader for images (`<img>`) used in a PHP/Blade template?

**Comment by herrstucki** [comment]
This is a webpack loader which is a tool to bundle resources in JavaScript. See https://webpack.js.org/

**Comment by herrstucki** [comment]
That said, it’s possible to use webpacked assets in PHP projects. Is this what you’re looking for?

**Comment by strarsis** [comment]
@herrstucki: Yes! I want to use it with the [sage 9.x](https://github.com/roots/sage) theme (for WordPress) 
which uses PHP (Blade) template files and webpack for building. Ideally I could just specify an `<img` with `srcset` (not from WordPress CMS but in theme!) and the responsive-loader should generate the right images.

**Comment by herrstucki** [comment]
@strarsis I'm not really sure if that's possible in the way you want. It is possible to export webpack-generated assets to JSON and import that in PHP with something like https://www.npmjs.com/package/webpack-manifest-plugin. But to export the srcset attributes generated by this loader you'd probably have to create a JS file which exports them to JSON and import those in PHP somehow …
