### ISSUE TITLE
Cannot find module when using vars in image path

### ISSUE THREAD

**Issue by 3dos** [herrstucki/responsive-loader#44]
I currently have the need to dynamically get images inducing `require` statements of strings concatenated with vars.

This loader works totally fine with statics assets but throws an error whit dynamic paths

```
import test from '../../images/orbital/ALL/0.jpg?size=1920'
console.log(test) // outputs the object
const test2 = require('../../images/orbital/ALL/0.jpg?size=1920')
console.log(test2) // outputs the object
const foo = 'ALL'
const test3 = require('../../images/orbital/' + foo + '/0.jpg?size=1920') // Error: Cannot find module
```

**Comment by herrstucki** [comment]
This isn‘t a problem with this loader. What you probably need is `require.context()`. Please refer to https://webpack.js.org/guides/dependency-management/

**Comment by 3dos** [comment]
Well, thank you very much! I'm quite new to webpack, that's why I posted this here. The guide helped me a lot. Thanks again for your help (and for this loader)

**Comment by digitaltopo** [comment]
@3dos If you were able to find a solution, do you care to share how you did this?

I keep getting the error `Error: Cannot find module...` whenever I append the sizes (`?sizes[]=768,sizes[]=1366,sizes[]=1920`) to my require statement:

```
const image = require(
        './' +
            imageName +
            '?sizes[]=768,sizes[]=1366,sizes[]=1920'
    );
```

I've also tried using a context:

```
const requireImages = require.context(
        'responsive-loader!../path/to/images/dir/',
        true,
        /\.(jpe?g|png)$/i
    );

   const image = requireImages(
        './' +
            imageName +
            '?sizes[]=768,sizes[]=1366,sizes[]=1920'
    );
```


```
