### ISSUE TITLE
Change output directory

### ISSUE THREAD

**Issue by tombeers** [herrstucki/responsive-loader#47]
I can't seem to find a way to change where the resulting files are output. At the moment they are all put in webpack's `output.path`, but in my case this isn't ideal. Is there any way to change this?

Many thanks

**Comment by alex-ketch** [comment]
Think you're looking for the [`context`](https://webpack.js.org/configuration/entry-context/#context) parameter.

You can get a feel for its rough usage in [this PR](https://github.com/herrstucki/responsive-loader/pull/12#issue-171322190)

**Comment by PeterKottas** [comment]
Hey @tombeers, did you manage to find a proper way to achieve this? I looked at context briefly but it's so poorly documented I didn't manage to find a way. There's also no mention of it here in the docs. @alex-ketch would you please be able to point me to the right way? I've tried 

```
test: /\.(png|jpg|jpeg|gif)$/,
                    use: {
                        loader: 'responsive-loader',
                        options: {
                            adapter: require('responsive-loader/sharp'),
                            placeholder: true,
                            placeholderSize: 50,
                            context: path.resolve(__dirname, clientBundleOutputDir, 'images')
                        }
                    }
```

But to no effect

**Comment by PeterKottas** [comment]
It took a bit of effort for me to figure it out so I though I'll provide my solution for the ones to come 

```
{
  test: /\.(png|jpg|jpeg|gif)$/,
  use: {
    loader: 'responsive-loader',
    options: {
      adapter: require('responsive-loader/sharp'),
      placeholder: true,
      placeholderSize: 50,
      name: 'images/[name]-[hash]-[width].[ext]'
    }
  }
}
```

**Comment by tombeers** [comment]
@PeterKottas ah brilliant, thank you for that

**Comment by tombeers** [comment]
Also, while I'm new to webpack, and so don't know if it's implicitly obvious that there's a name property, it would be nice if it was listed in the readme.

**Comment by herrstucki** [comment]
@tombeers @PeterKottas I've documented the missing options in #48. I also updated the `context` implementation to be the same as file-loader. That said, file-loader has another option `outputPath` which does something similar but not the same thing? @alex-ketch any idea what the difference exactly is?
