### ISSUE TITLE
File not found when generated from CSS

### ISSUE THREAD

**Issue by klcantrell** [herrstucki/responsive-loader#49]
"responsive-loader": "^1.1.0"
"webpack": "^3.10.0"

Great loader, much thanks.  One issue I'm finding is when an image is created from a CSS url, a path to the resource is generated that can't be found.  To clarify, an image with the correct name gets created however it gets a path that can't be found.  However, an image created from importing in a JS file is located fine.

Example of a path generated from within a JS file:
file:///C:/Users/kcantrell/Desktop/offline-dev-projects/practice-router/dist/imgs/cloud-200.jpg

Example of a path generated from a CSS url:
file:///C:/Userskcantrell%C3%9Esktopoffline-dev-projectspractice-router/dist/imgs/calculator-background-700.jpg

Is this a bug or perhaps am I missing something and there's some configuration I need to do to get CSS urls to work with the loader.  Webpack config below:

```
const path = require('path'),
			ExtractTextPlugin = require('extract-text-webpack-plugin'),
			CompressionPlugin = require('compression-webpack-plugin'),
			webpack = require('webpack');

module.exports = {
	entry: {
		app: './src/js/index.js'
	},
	output: {
		path: __dirname + '/dist',
		publicPath: __dirname + '/dist/',
		filename: "[name].bundle.js",
		chunkFilename: "[name].bundle.js"
	},
	module: {
	    rules: [
			{
			      test: /\.js$/,
			      include: path.resolve(__dirname, 'src/js'),
			      use: [{
			        loader: 'babel-loader',
			        options: {
			          presets: [
			            ['env', { modules: false }]
			          ]
			        }
			      }]
			    },
		      {
		        test: /\.(png|jpg|gif)$/,
		        use: {
		        	loader: 'responsive-loader',
		        	options: {
		        		name: 'imgs/[name]-[width].[ext]'
		        	}
		        }
		      },
		      {
		        test: /\.css$/,
		        exclude: path.resolve(__dirname, 'src/css'),
		        loader: 'css-loader',
		        options: {
		        	minimize: true
		        }
		      },
		      {
		        test: /\.css$/,
		        include: path.resolve(__dirname, 'src/css'),
		        loader: ExtractTextPlugin.extract(
		        	{use: [
		        		{ loader: 'css-loader',
		        			options: { minimize: true } 
		        		}
                                 ]}
                         )
		      }
	    ]
	},
  plugins: [
    new ExtractTextPlugin("app.css"),
    new webpack.optimize.CommonsChunkPlugin({
				name: 'commons',
				filename: 'commons.js'
		}),
		new webpack.optimize.LimitChunkCountPlugin({
		  maxChunks: 6
		  // minChunkSize: 1000
		})
  ]
}
```

**Comment by klcantrell** [comment]
I think I figured it out.  I changed `output.publicPath` from `__dirname + '/dist/'` to just `'dist/'` and that fixed the problem.  All paths generated by responsive-loader work and pull in the resized images.

Admittedly, I don't know exactly why this didn't cause a problem with the other images imported into JS files, but I'm just going to go with it and hopefully learn the reasons as I go.  Thanks again!

**Comment by herrstucki** [comment]
@klcantrell For what it's worth, you should always use Node's [`path.join()`](https://nodejs.org/api/path.html#path_path_join_paths) function to construct paths to avoid platform-specific issues with path separators, `/` vs. `\`.

E.g. `__dirname + 'dist/'` becomes `path.join(__dirname, 'dist')`

**Comment by klcantrell** [comment]
@herrstucki Thank you, I'll be sure to start making that a habit!
