### ISSUE TITLE
Background: '#FFFFFF' forces ALL transparent PNGs to white

### ISSUE THREAD

**Issue by drtimofey** [herrstucki/responsive-loader#50]
Expected behavior:
When I set Background: '#FFFFFF' I expect white background ONLY on JPGs converted from transparent PNGs.

Current behavior:
Applies white background to ALL transparent PNGs, not just the ones being converted to JPGs.

I am using the Sharp adapter.

**Comment by herrstucki** [comment]
You can add background colors to individual images, see https://github.com/herrstucki/responsive-loader/blob/master/test/sharp/index.js#L43. So instead of setting background globally for all images, I recommend to set it per image.
