### ISSUE TITLE
Allow to pass different resize modes to Jimp

### ISSUE THREAD

**Issue by saitonakamura** [herrstucki/responsive-loader#55]
Jimp can resize images using [different modes](https://github.com/oliver-moran/jimp#resize-modes). I suggest to add another option to pass with adapter settings.

**Comment by strarsis** [comment]
@herrstucki: +1, sharp [also supports this](http://sharp.dimens.io/en/stable/api-resize/).

**Comment by saitonakamura** [comment]
Let's close it as stale
