### ISSUE TITLE
How to handle `responsive-loader` with jest/CRA?

### ISSUE THREAD

**Issue by bitttttten** [herrstucki/responsive-loader#86]
I am using CRA with responsive-loader, and I am getting the following errors:

```sh
 FAIL  src/pages/User/test.tsx
  ● Test suite failed to run

    Cannot find module './assets/user_background.jpg?min=320&max=800&steps=3' from 'index.tsx'

    However, Jest was able to find:
        './index.tsx'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      20 | 
    > 21 | const userBackground = require('./assets/user_background.jpg?min=320&max=800&steps=3')
         |                        ^
      22 | 
```

Are there any solutions to fix the test?

The only way around it I can find it edit my import into `const userBackground = require('./assets/user_background.jpg')` and so not having any benefits of the loader.

**Comment by herrstucki** [comment]
CRA generates a Jest config that mocks certain extensions to empty modules. The patterns don't account for the query string part (the `?min=...` part) See here:

https://github.com/facebook/create-react-app/blob/9d70c7afab377c4bec76aa177fadab476ebb115b/packages/react-scripts/scripts/utils/createJestConfig.js#L40-L48

You'd have to change your Jest config to also mock the paths used by responsive-loader.

More infos here: https://jestjs.io/docs/en/webpack#mocking-css-modules

**Comment by bitttttten** [comment]
I was digging into that exact line, although it confused me as the fileTransform file includes logic for handling svg files, although `svg` is not inside the regex. Nor is jpg, jpeg, webp, or png.

So patching the transform key is the way to go here?

**Comment by herrstucki** [comment]
It looks like the regexp matches everything _except_ js, jsx etc. … why it doesn't match foo.jpg?bar I can't really tell 🤔

**Comment by herrstucki** [comment]
OK, so it seems that it's really an issue of Jest itself: https://github.com/facebook/jest/issues/4181

I'll close this issue since we can't really do anything about that, sorry!

**Comment by bitttttten** [comment]
So it's an issue with jest. If I solve it, I'll come back here and update my issue for anyone coming from Google :, )

**Comment by bitttttten** [comment]
I ended up applying the `babel-plugin-import-remove-resource-query` plugin to jest, and then mocked the file inside the test:

```
jest.mock('../assets/user_background.jpg', () => ({
    src: '',
    srcSet: '',
    width: 1,
    height: 1,
}))
```

**Comment by kopax** [comment]
While using [`responsive-loader`](https://github.com/dazuaz/responsive-loader), I get all my unit test failing in Jest during the import of an image with format webp: `?format=web`:

```jsx
Cannot find module '../images/11_1920-xl.jpg?format=webp' from 'src/Home.js';
```

How can I use both jest and responsive-loader webp? Your solution seems to be really problematic.
